### ISSUE TITLE
Compiler error with 7.8.4

### ISSUE THREAD

**Issue by ghost** [atzeus/FRPNow#17]
Getting the following compile error with 7.8.4:

Control/FRPNow/Core.hs:624:76:
    Can't make a derived instance of
      ‘Typeable FRPWaitsForNeverException’:
      You need DeriveDataTypeable to derive an instance for this class
    In the data declaration for ‘FRPWaitsForNeverException’

**Comment by atzeus** [comment]
Which version? I think from 0.16 this error should be fixed.  Can you confirm?

**Comment by ghost** [comment]
Atze,

Well, it works with 0.17. I did a git pull an hour ago (when I found the cabal rev issue) and the compile failed. I pulled again, and it compiles.

Perhaps you working faster than I can pull :-)

Anyway, seems ok now.

Mike

**Comment by atzeus** [comment]
:) Cheers  :)
