### ISSUE TITLE
understanding Behavior (Behavior a)

### ISSUE THREAD

**Issue by ninegua** [atzeus/FRPNow#19]
Hi Atze, it was nice chatting with you at lunch. Here is some code that I adapted from your sample program, trying to learn how I can define recursive behaviors using `integrate`, which returns a type of `Behavior (Behavior a)`. The natural way of getting a single `Behavior a` was to use `join` since `Behavior` is a monad, however, it wouldn't work (see `e'` below). I had to resort to recursive monads and go through conversion from `Behavior` to `Now` monad in order to get a working definition (see `e` below). Any explanation is greatly appreciated!

``` haskell
{-# LANGUAGE RecursiveDo #-}
import Control.Monad (join)
import Control.FRPNow
import Control.Applicative

n = 1000

main = runNowMaster (test n)

test :: Int -> Now (Event ())
test n = do b <- count 
            let time = fmap ((*0.001) . fromIntegral) b
{- Recursively define an exponential signal -}
            rec e <- sample $ delayTime time (1.0::Double) e >>= integrate time 
            traceChanges "e = " e
{- however, the following doesn't work, and is constant -}
            let e' = join $ delayTime time (1.0::Double) e' >>= integrate time 
            traceChanges "e' = " e'
            stop <- sample (when ((n ==) <$> b))
            return stop

count :: Now (Behavior Int)
count = loop 0 where
  loop i =  do  e <- async (return ())
                e'<- planNow (loop (i+1) <$ e)
                return (pure i `switch` e')
```

My interest in this definition goes back to my early paper [Plugging a Space Leak with an Arrow](http://thev.net/PaulLiu/download/leak.pdf) where it can be demonstrated that if using the function denotation of a signal (`Time -> a`) in an implementation, a space leak cannot be avoided under the call-by-need evaluation strategy. FRPNow obviously doesn't have this issue, but I'm just confused as in why it is useful to make `Behavior` a monad.

**Comment by atzeus** [comment]
Hi!

If I understand your question correctly, you're asking why if we have:

```
  countChanges :: Eq a => Behavior a -> Behavior (Behavior Int)
```

then 

```
 join countChanges 
```

gives a behavior that is always 0.

The answer is that countChanges gives a Behavior (Behavior a), meaning that the amount of changes that we see depends on when we started counting.

If we do 

```
     join countChanges
```

this gives a behavior that at any point in time, gives the number of changes if we start counting at that time, which is always zero. This all follows from the denotation semantics.

The same reasoning holds for integration.

Why is it then  useful to have a monad instance for behavior? Consider the definition of change:

```
 change :: Eq a => Behavior a -> Behavior (Event ())
 change b = do cur <- b
                         when ((cur /=) <$> b)
```

Here we sample b, to decide which other behavior to sample namely, when ... 
Note we cannot use just applicative for this.

Does this answer you question?
