### ISSUE TITLE
"Trivial" program results in "thread blocked indefinitely in an MVar operation"

### ISSUE THREAD

**Issue by ocharles** [atzeus/FRPNow#2]
The following:

``` haskell
module Main where

import Control.FRPNow

main :: IO ()
main = runNowMaster (return never)
```

When compiled (with `ghc --make -threaded`) results in 

```
Test: thread blocked indefinitely in an MVar operation
```

when executed.

**Comment by atzeus** [comment]
This is due to nothing actually happening. GHC runtime will detect that and then throw this error. I'll see if I can prevent it.

**Comment by atzeus** [comment]
Fixed! This will print the following in the next release:

FRP System has become inactive because nothing else is going to happen.We could keep on waiting forever, but instead we will just exit the FRP system now...Bye!

**Comment by Xandaros** [comment]
I was interested in how you implemented this, but I can't actually find the commit. Where was this done?

**Comment by atzeus** [comment]
Whoops, forgot to push. The code is at work, I'll push it tomorrow. Essentially, I catch an Indefinitly blocked on MVar exception.

**Comment by int-index** [comment]
@atzeus What if I want to catch it myself? I think throwing an exception is a sensible behavior, it just needs to be documented.

**Comment by atzeus** [comment]
Hmm, you're right. I propose throwing a FRPNowInactive exception, and documenting it. Agreed?

**Comment by int-index** [comment]
@atzeus Agreed, if you're sure that you can't accidentally catch exceptions thrown due to user-defined `MVar`s (as opposed to `MVar`s used by FRPNow internally).

**Comment by atzeus** [comment]
Sadly, I can't guarantee that, since IndefinitlyBlockedOnMVar exception does not tell which MVar is involved :( I propose I document that as well..

**Comment by int-index** [comment]
Throwing `FRPNowInactive` when the thread is blocked on a user-defined `MVar` isn't better than throwing `IndefinitelyBlockedOnMVar` when the FRP system is inactive.

I think it's better not to mess with this and just document that when the FRP system becomes inactive, an MVar exception may be thrown.

**Comment by atzeus** [comment]
Agreed. I propose I just dump a message to standard error saying that the following exception may be due to the FRP system becoming inactive and (re)throw the indefinitly blocked on MVar exception. Agreed?

**Comment by int-index** [comment]
I don't like libraries doing IO without my consent or explicit command. Messages are something the user can see, but this message is targeted at the developer.

But that's just me.

**Comment by atzeus** [comment]
I just realized that it is actually possible to guarantee that a FRPSystemInactive exception comes from the FRPNow MVar instead of a user defined MVar, so I will just do that :)

**Comment by int-index** [comment]
Perfect! :)

**Comment by atzeus** [comment]
Commited!
