### ISSUE TITLE
MonadIO Now?

### ISSUE THREAD

**Issue by ocharles** [atzeus/FRPNow#9]
There is a potential instance

``` haskell
instance MonadIO Now where
  liftIO = sync
```

What do you think about adding this? It would nicely simplify working in the `Now` monad if you happen to have stuff that is already polymorphic over `MonadIO m`.

**Comment by atzeus** [comment]
Sounds good, adding it now! Cheers

**Comment by atzeus** [comment]
Added it, it will be in the next release!
